### ISSUE TITLE
Add example to custom hiera

### ISSUE THREAD

**Issue by lbetz** [NETWAYS/icinga-installer#27]
- mysql tuning
- pgsql tuning
- apache tls
- icinga server connection to a worker

**Comment by lbetz** [comment]
wrong commit, sorry.

**Comment by RincewindsHat** [comment]
Examples for agent setup please.

**Comment by lbetz** [comment]
> Examples for agent setup please.

No. An agent is installed completly by the scenario agent and has no need for additional hiera data.
