### ISSUE TITLE
Web-Setup misconfigures apache2 on Debian-ish systems

### ISSUE THREAD

**Issue by RincewindsHat** [NETWAYS/icinga-installer#36]
The default configuration directory layout for `apache2` on Debian uses `conf-available` and `conf-enabled` directories instead of `conf.d` to store configuration.
After running the setup the `apache2.conf` file is missing an include of the `conf-enabled` directory, which gets therefore ignored.

**Comment by lbetz** [comment]
Apache is managed by the puppet module puppetlabs-apache and this is the default behavior of this module.
