### ISSUE TITLE
Missing `UTF8` setting in database ressources for icingaweb2

### ISSUE THREAD

**Issue by RincewindsHat** [NETWAYS/icinga-installer#62]

**Comment by lbetz** [comment]
It is not describe as a requirement, it is up to you to provide such a database or to configure your DBMS accordingly. See, e.g.

https://icinga.com/docs/icinga-web/latest/doc/02-Installation/01-Debian/

**Comment by RincewindsHat** [comment]
Sorry for the missing information, but afaik the default setting for the icingadb database is indeed UTF8 and I think it would be helpful if that would already be the default for the corresponding ressource in Icingaweb2.
I fell over this today, it caused problems in another component.

**Comment by lbetz** [comment]
Ah, ok. The default for charset is undef, depends on the puppet-icingaweb2 module. But almost everything is freely configurable. Use

icingaweb2::module::icingadb::db_charset: UTF8

in /etc/icinga-installer/custom-hiera.yaml.

**Comment by lbetz** [comment]
... and you're right, in puppet-icinga the icingadb resource should has to be set to UTF8, because the database (in this module) is setup with UTF8.

**Comment by lbetz** [comment]
refs icinga/puppet-icinga#86

**Comment by lbetz** [comment]
module icinga/puppet-icinga has to be updated to v3.2.1

**Comment by lbetz** [comment]
refs #63

**Comment by RincewindsHat** [comment]
Thanks :-)
