### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by 00buc** [NETWAYS/icinga-installer#69]
<pre>
root@debian11:~/icinga-installer-main/bin# wget https://apt.puppet.com/puppet7-release-bullseye.deb
--2023-04-30 05:10:52--  https://apt.puppet.com/puppet7-release-bullseye.deb
Auflösen des Hostnamens apt.puppet.com (apt.puppet.com)… 99.84.146.98, 99.84.146.71, 99.84.146.60, ...
Verbindungsaufbau zu apt.puppet.com (apt.puppet.com)|99.84.146.98|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 11726 (11K) [application/x-debian-package]
Wird in »puppet7-release-bullseye.deb« gespeichert.

puppet7-release-bullseye.deb  100%[=================================================>]  11,45K  --.-KB/s    in 0s

2023-04-30 05:10:52 (133 MB/s) - »puppet7-release-bullseye.deb« gespeichert [11726/11726]

root@debian11:~/icinga-installer-main/bin# dpkg -i puppet7-release-bullseye.deb
dpkg: Warnung: Version 7.0.0-11buster des Paketes puppet7-release wird durch ältere Version 7.0.0-11bullseye ersetzt
(Lese Datenbank ... 51838 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von puppet7-release-bullseye.deb ...
Entpacken von puppet7-release (7.0.0-11bullseye) über (7.0.0-11buster) ...
puppet7-release (7.0.0-11bullseye) wird eingerichtet ...
Neue Version der Konfigurationsdatei /etc/apt/sources.list.d/puppet7.list wird installiert ...
root@debian11:~/icinga-installer-main/bin# ./icinga-installer -S server-db-pgsql
Traceback (most recent call last):
        2: from ./icinga-installer:3:in `<main>'
        1: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- kafo (LoadError)
</pre>

### Was sagt diese Meldung aus? und wie bekommt man die super "easy to use Installation" zum laufen? 
Puppet installieren reicht offenbar nicht

**Comment by lbetz** [comment]
Hi Thomas,

no, installing Puppet alone is not enough. Please follow the instructions in https://github.com/NETWAYS/icinga-installer/blob/main/doc/01-Installation.md for Debian Buster.
The repository packages.netways.com/extras is also required. The error message says that kafo, a ruby gem, is not installed.

Bye
Lennart

**Comment by 00buc** [comment]
Vielen Dank Lennard,
die Anleitung  https://github.com/NETWAYS/icinga-installer/blob/main/doc/01-Installation.md hat weiter geholfen, ist jedoch unvollständig, zumindest wenn man ein [Debian 11 "bullseye"] verwendet.

Ich habe es nach der vorgeschlagenen Anleitung versucht und eine frisch installierte [Debian 11 "bullseye"] VM verwendet. Schon der erste Schritt der Anleitung schlug fehl. sudo ist wohl nicht Teil einer Sandardinstallation. also "schnell apt install sudo" dann gab es diese Fehlermeldung:

-----
<pre>
root@debian11:~# wget -O - https://packages.netways.de/netways-repo.asc | sudo apt-key add -
--2023-05-02 05:36:58--  https://packages.netways.de/netways-repo.asc
Auflösen des Hostnamens packages.netways.de (packages.netways.de)… 185.233.188.234
Verbindungsaufbau zu packages.netways.de (packages.netways.de)|185.233.188.234|:443 … verbunden.
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 1660 (1,6K) [application/pgp-keys]
Wird in »STDOUT« gespeichert.

-                              0%[                                              ]       0  --.-KB/s    in 0s


Schreiben nach »-« nicht möglich (Datenübergabe unterbrochen (broken pipe)).
</pre>
-----
nachdem sudo, gnupg1 und gnupg2 nachinstalliert wurden, funktioniert es nach Anleitung,

-----
<pre>
root@debian11:~# icinga-installer -S server-db-pgsql
Preparing installation Done
  Success!
      Initial credentials are icingaadmin / ????????????

  The full log is at /var/log/icinga-installer/server-db-pgsql.log
</pre>
-----

"Installation Erfolgreich"


in die Anleitung zu bullseye gehört wohl als erster Schritt sowas wie

**apt install sudo  gnupg2 gnupg1**


Vielen Dank
Gruß thomas

**Comment by martialblog** [comment]
Hi, Danke für den Hinweis. Wir werden die Installations Doku etwas prominenter verlinken.

**Comment by 00buc** [comment]
Hallo Markus,
vielen Dank,  mit einem freundlichen Hinweis habe ich schließlich die Anleitung im Github gefunden und auch noch meine Beobachtungen über notwendige Pakete beschrieben. Schließlich hat die Installation sehr gut Funktioniert.
 
 
 
beste Grüße
Buchroth, thomas
 
 
 
 
 
                |//
               (o o) 
 +-------oOO----(_)---OOo------+ 
  Buchroth, thomas 
  An den Eichen 1  in  Kränzlin 
  [ osm.org/go/0McSFFnwB ] 
  Telefon +49 . 3391 . 404029 
  Mobil   +49 . 176 . 21473969 
  FAX     +49 . 3391 . 404027 
 +-----------------------------+ 
  
PS. Alle Tippfehler dienen auschließlich der Belustigung des Lesers.
 
 

Gesendet: Dienstag, 02. Mai 2023 um 08:43 Uhr
Von: "Markus Opolka" ***@***.***>
An: "NETWAYS/icinga-installer" ***@***.***>
Cc: "thomas" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [NETWAYS/icinga-installer] Fehlermeldung (Issue #69)
 
Hi, Danke für den Hinweis. Wir werden die Installations Doku etwas prominenter verlinken.

**Comment by martialblog** [comment]
Habe die README entsprechend erweitert und explizit auf den doc/ Ordner vewiesen. 

Lass uns wissen, wenn es noch Probleme gibt.

Danke und Grüße
