### ISSUE TITLE
Add Debian Bookworm Support

### ISSUE THREAD

**Issue by tgrymatt** [NETWAYS/icinga-installer#74]
Is there any planed release date for Icinga-Installer on Debian 12 Bookworm? Can´t find it in this repo: https://packages.netways.de/extras/debian/pool/main/i/icinga-installer/

**Comment by lbetz** [comment]
Sure, but first we need a test and development environment and our package build system has to support bookworm. And of course all related puppet modules have to run on bookworm. It will take some times.
